// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializehostTransferredPayload")
public inline fun hostTransferredPayload(block: com.joymusic.music.listentogether.proto.HostTransferredPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload =
  com.joymusic.music.listentogether.proto.HostTransferredPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.HostTransferredPayload`
 */
public object HostTransferredPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload = _builder.build()

    /**
     * `string oldHostId = 1;`
     */
    public var oldHostId: kotlin.String
      @kotlin.jvm.JvmName("getOldHostId")
        get() = _builder.oldHostId
      @kotlin.jvm.JvmName("setOldHostId")
        set(value) {
        _builder.oldHostId = value
      }
    /**
     * `string oldHostId = 1;`
     */
    public fun clearOldHostId() {
      _builder.clearOldHostId()
    }

    /**
     * `string newHostId = 2;`
     */
    public var newHostId: kotlin.String
      @kotlin.jvm.JvmName("getNewHostId")
        get() = _builder.newHostId
      @kotlin.jvm.JvmName("setNewHostId")
        set(value) {
        _builder.newHostId = value
      }
    /**
     * `string newHostId = 2;`
     */
    public fun clearNewHostId() {
      _builder.clearNewHostId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload.copy(block: `com.joymusic.music.listentogether.proto`.HostTransferredPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.HostTransferredPayload =
  `com.joymusic.music.listentogether.proto`.HostTransferredPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

