// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializejoinedRoomPayload")
public inline fun joinedRoomPayload(block: com.joymusic.music.listentogether.proto.JoinedRoomPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload =
  com.joymusic.music.listentogether.proto.JoinedRoomPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.JoinedRoomPayload`
 */
public object JoinedRoomPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload = _builder.build()

    /**
     * `string sessionToken = 1;`
     */
    public var sessionToken: kotlin.String
      @kotlin.jvm.JvmName("getSessionToken")
        get() = _builder.sessionToken
      @kotlin.jvm.JvmName("setSessionToken")
        set(value) {
        _builder.sessionToken = value
      }
    /**
     * `string sessionToken = 1;`
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }

    /**
     * `.listentogether.RoomState roomState = 2;`
     */
    public var roomState: com.joymusic.music.listentogether.proto.Listentogether.RoomState
      @kotlin.jvm.JvmName("getRoomState")
        get() = _builder.roomState
      @kotlin.jvm.JvmName("setRoomState")
        set(value) {
        _builder.roomState = value
      }
    /**
     * `.listentogether.RoomState roomState = 2;`
     */
    public fun clearRoomState() {
      _builder.clearRoomState()
    }
    /**
     * `.listentogether.RoomState roomState = 2;`
     * @return Whether the roomState field is set.
     */
    public fun hasRoomState(): kotlin.Boolean {
      return _builder.hasRoomState()
    }

    public val JoinedRoomPayloadKt.Dsl.roomStateOrNull: com.joymusic.music.listentogether.proto.Listentogether.RoomState?
      get() = _builder.roomStateOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload.copy(block: `com.joymusic.music.listentogether.proto`.JoinedRoomPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayload =
  `com.joymusic.music.listentogether.proto`.JoinedRoomPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.joymusic.music.listentogether.proto.Listentogether.JoinedRoomPayloadOrBuilder.roomStateOrNull: com.joymusic.music.listentogether.proto.Listentogether.RoomState?
  get() = if (hasRoomState()) getRoomState() else null

