// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializereconnectedPayload")
public inline fun reconnectedPayload(block: com.joymusic.music.listentogether.proto.ReconnectedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload =
  com.joymusic.music.listentogether.proto.ReconnectedPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.ReconnectedPayload`
 */
public object ReconnectedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload = _builder.build()

    /**
     * `string roomCode = 1;`
     */
    public var roomCode: kotlin.String
      @kotlin.jvm.JvmName("getRoomCode")
        get() = _builder.roomCode
      @kotlin.jvm.JvmName("setRoomCode")
        set(value) {
        _builder.roomCode = value
      }
    /**
     * `string roomCode = 1;`
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * `string userId = 2;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 2;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `.listentogether.RoomState state = 3;`
     */
    public var state: com.joymusic.music.listentogether.proto.Listentogether.RoomState
      @kotlin.jvm.JvmName("getState")
        get() = _builder.state
      @kotlin.jvm.JvmName("setState")
        set(value) {
        _builder.state = value
      }
    /**
     * `.listentogether.RoomState state = 3;`
     */
    public fun clearState() {
      _builder.clearState()
    }
    /**
     * `.listentogether.RoomState state = 3;`
     * @return Whether the state field is set.
     */
    public fun hasState(): kotlin.Boolean {
      return _builder.hasState()
    }

    public val ReconnectedPayloadKt.Dsl.stateOrNull: com.joymusic.music.listentogether.proto.Listentogether.RoomState?
      get() = _builder.stateOrNull

    /**
     * `bool isHost = 4;`
     */
    public var isHost: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsHost")
        get() = _builder.isHost
      @kotlin.jvm.JvmName("setIsHost")
        set(value) {
        _builder.isHost = value
      }
    /**
     * `bool isHost = 4;`
     */
    public fun clearIsHost() {
      _builder.clearIsHost()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload.copy(block: `com.joymusic.music.listentogether.proto`.ReconnectedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayload =
  `com.joymusic.music.listentogether.proto`.ReconnectedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.joymusic.music.listentogether.proto.Listentogether.ReconnectedPayloadOrBuilder.stateOrNull: com.joymusic.music.listentogether.proto.Listentogether.RoomState?
  get() = if (hasState()) getState() else null

