// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeroomState")
public inline fun roomState(block: com.joymusic.music.listentogether.proto.RoomStateKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.RoomState =
  com.joymusic.music.listentogether.proto.RoomStateKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.RoomState.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.RoomState`
 */
public object RoomStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.RoomState.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.RoomState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.RoomState = _builder.build()

    /**
     * `string roomCode = 1;`
     */
    public var roomCode: kotlin.String
      @kotlin.jvm.JvmName("getRoomCode")
        get() = _builder.roomCode
      @kotlin.jvm.JvmName("setRoomCode")
        set(value) {
        _builder.roomCode = value
      }
    /**
     * `string roomCode = 1;`
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * `string hostId = 2;`
     */
    public var hostId: kotlin.String
      @kotlin.jvm.JvmName("getHostId")
        get() = _builder.hostId
      @kotlin.jvm.JvmName("setHostId")
        set(value) {
        _builder.hostId = value
      }
    /**
     * `string hostId = 2;`
     */
    public fun clearHostId() {
      _builder.clearHostId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UsersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     */
     public val users: com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.usersList
      )
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUsers")
    public fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>.add(value: com.joymusic.music.listentogether.proto.Listentogether.UserInfo) {
      _builder.addUsers(value)
    }
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>.plusAssign(value: com.joymusic.music.listentogether.proto.Listentogether.UserInfo) {
      add(value)
    }
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUsers")
    public fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>.addAll(values: kotlin.collections.Iterable<com.joymusic.music.listentogether.proto.Listentogether.UserInfo>) {
      _builder.addAllUsers(values)
    }
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>.plusAssign(values: kotlin.collections.Iterable<com.joymusic.music.listentogether.proto.Listentogether.UserInfo>) {
      addAll(values)
    }
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     * @param index The index to set the value at.
     * @param value The users to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUsers")
    public operator fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>.set(index: kotlin.Int, value: com.joymusic.music.listentogether.proto.Listentogether.UserInfo) {
      _builder.setUsers(index, value)
    }
    /**
     * `repeated .listentogether.UserInfo users = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearUsers")
    public fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.UserInfo, UsersProxy>.clear() {
      _builder.clearUsers()
    }

    /**
     * `.listentogether.TrackInfo currentTrack = 4;`
     */
    public var currentTrack: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo
      @kotlin.jvm.JvmName("getCurrentTrack")
        get() = _builder.currentTrack
      @kotlin.jvm.JvmName("setCurrentTrack")
        set(value) {
        _builder.currentTrack = value
      }
    /**
     * `.listentogether.TrackInfo currentTrack = 4;`
     */
    public fun clearCurrentTrack() {
      _builder.clearCurrentTrack()
    }
    /**
     * `.listentogether.TrackInfo currentTrack = 4;`
     * @return Whether the currentTrack field is set.
     */
    public fun hasCurrentTrack(): kotlin.Boolean {
      return _builder.hasCurrentTrack()
    }

    public val RoomStateKt.Dsl.currentTrackOrNull: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo?
      get() = _builder.currentTrackOrNull

    /**
     * `bool isPlaying = 5;`
     */
    public var isPlaying: kotlin.Boolean
      @kotlin.jvm.JvmName("getIsPlaying")
        get() = _builder.isPlaying
      @kotlin.jvm.JvmName("setIsPlaying")
        set(value) {
        _builder.isPlaying = value
      }
    /**
     * `bool isPlaying = 5;`
     */
    public fun clearIsPlaying() {
      _builder.clearIsPlaying()
    }

    /**
     * `int64 position = 6;`
     */
    public var position: kotlin.Long
      @kotlin.jvm.JvmName("getPosition")
        get() = _builder.position
      @kotlin.jvm.JvmName("setPosition")
        set(value) {
        _builder.position = value
      }
    /**
     * `int64 position = 6;`
     */
    public fun clearPosition() {
      _builder.clearPosition()
    }

    /**
     * `int64 lastUpdate = 7;`
     */
    public var lastUpdate: kotlin.Long
      @kotlin.jvm.JvmName("getLastUpdate")
        get() = _builder.lastUpdate
      @kotlin.jvm.JvmName("setLastUpdate")
        set(value) {
        _builder.lastUpdate = value
      }
    /**
     * `int64 lastUpdate = 7;`
     */
    public fun clearLastUpdate() {
      _builder.clearLastUpdate()
    }

    /**
     * `float volume = 8;`
     */
    public var volume: kotlin.Float
      @kotlin.jvm.JvmName("getVolume")
        get() = _builder.volume
      @kotlin.jvm.JvmName("setVolume")
        set(value) {
        _builder.volume = value
      }
    /**
     * `float volume = 8;`
     */
    public fun clearVolume() {
      _builder.clearVolume()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QueueProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     */
     public val queue: com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.queueList
      )
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addQueue")
    public fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.add(value: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo) {
      _builder.addQueue(value)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     * @param value The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(value: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo) {
      add(value)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllQueue")
    public fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.addAll(values: kotlin.collections.Iterable<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo>) {
      _builder.addAllQueue(values)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     * @param values The queue to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllQueue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.plusAssign(values: kotlin.collections.Iterable<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo>) {
      addAll(values)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     * @param index The index to set the value at.
     * @param value The queue to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setQueue")
    public operator fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.set(index: kotlin.Int, value: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo) {
      _builder.setQueue(index, value)
    }
    /**
     * `repeated .listentogether.TrackInfo queue = 9;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearQueue")
    public fun com.google.protobuf.kotlin.DslList<com.joymusic.music.listentogether.proto.Listentogether.TrackInfo, QueueProxy>.clear() {
      _builder.clearQueue()
    }

    /**
     * `int64 revision = 10;`
     */
    public var revision: kotlin.Long
      @kotlin.jvm.JvmName("getRevision")
        get() = _builder.revision
      @kotlin.jvm.JvmName("setRevision")
        set(value) {
        _builder.revision = value
      }
    /**
     * `int64 revision = 10;`
     */
    public fun clearRevision() {
      _builder.clearRevision()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.RoomState.copy(block: `com.joymusic.music.listentogether.proto`.RoomStateKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.RoomState =
  `com.joymusic.music.listentogether.proto`.RoomStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.joymusic.music.listentogether.proto.Listentogether.RoomStateOrBuilder.currentTrackOrNull: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo?
  get() = if (hasCurrentTrack()) getCurrentTrack() else null

