// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeroomCreatedPayload")
public inline fun roomCreatedPayload(block: com.joymusic.music.listentogether.proto.RoomCreatedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload =
  com.joymusic.music.listentogether.proto.RoomCreatedPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.RoomCreatedPayload`
 */
public object RoomCreatedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload = _builder.build()

    /**
     * `string roomCode = 1;`
     */
    public var roomCode: kotlin.String
      @kotlin.jvm.JvmName("getRoomCode")
        get() = _builder.roomCode
      @kotlin.jvm.JvmName("setRoomCode")
        set(value) {
        _builder.roomCode = value
      }
    /**
     * `string roomCode = 1;`
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * `string userId = 2;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 2;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string sessionToken = 3;`
     */
    public var sessionToken: kotlin.String
      @kotlin.jvm.JvmName("getSessionToken")
        get() = _builder.sessionToken
      @kotlin.jvm.JvmName("setSessionToken")
        set(value) {
        _builder.sessionToken = value
      }
    /**
     * `string sessionToken = 3;`
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }

    /**
     * `.listentogether.RoomState roomState = 4;`
     */
    public var roomState: com.joymusic.music.listentogether.proto.Listentogether.RoomState
      @kotlin.jvm.JvmName("getRoomState")
        get() = _builder.roomState
      @kotlin.jvm.JvmName("setRoomState")
        set(value) {
        _builder.roomState = value
      }
    /**
     * `.listentogether.RoomState roomState = 4;`
     */
    public fun clearRoomState() {
      _builder.clearRoomState()
    }
    /**
     * `.listentogether.RoomState roomState = 4;`
     * @return Whether the roomState field is set.
     */
    public fun hasRoomState(): kotlin.Boolean {
      return _builder.hasRoomState()
    }

    public val RoomCreatedPayloadKt.Dsl.roomStateOrNull: com.joymusic.music.listentogether.proto.Listentogether.RoomState?
      get() = _builder.roomStateOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload.copy(block: `com.joymusic.music.listentogether.proto`.RoomCreatedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayload =
  `com.joymusic.music.listentogether.proto`.RoomCreatedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.joymusic.music.listentogether.proto.Listentogether.RoomCreatedPayloadOrBuilder.roomStateOrNull: com.joymusic.music.listentogether.proto.Listentogether.RoomState?
  get() = if (hasRoomState()) getRoomState() else null

