// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeserverCapabilities")
public inline fun serverCapabilities(block: com.joymusic.music.listentogether.proto.ServerCapabilitiesKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities =
  com.joymusic.music.listentogether.proto.ServerCapabilitiesKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.ServerCapabilities`
 */
public object ServerCapabilitiesKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities = _builder.build()

    /**
     * `bool supportsProtobuf = 1;`
     */
    public var supportsProtobuf: kotlin.Boolean
      @kotlin.jvm.JvmName("getSupportsProtobuf")
        get() = _builder.supportsProtobuf
      @kotlin.jvm.JvmName("setSupportsProtobuf")
        set(value) {
        _builder.supportsProtobuf = value
      }
    /**
     * `bool supportsProtobuf = 1;`
     */
    public fun clearSupportsProtobuf() {
      _builder.clearSupportsProtobuf()
    }

    /**
     * `bool supportsCompression = 2;`
     */
    public var supportsCompression: kotlin.Boolean
      @kotlin.jvm.JvmName("getSupportsCompression")
        get() = _builder.supportsCompression
      @kotlin.jvm.JvmName("setSupportsCompression")
        set(value) {
        _builder.supportsCompression = value
      }
    /**
     * `bool supportsCompression = 2;`
     */
    public fun clearSupportsCompression() {
      _builder.clearSupportsCompression()
    }

    /**
     * `string serverVersion = 3;`
     */
    public var serverVersion: kotlin.String
      @kotlin.jvm.JvmName("getServerVersion")
        get() = _builder.serverVersion
      @kotlin.jvm.JvmName("setServerVersion")
        set(value) {
        _builder.serverVersion = value
      }
    /**
     * `string serverVersion = 3;`
     */
    public fun clearServerVersion() {
      _builder.clearServerVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities.copy(block: `com.joymusic.music.listentogether.proto`.ServerCapabilitiesKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.ServerCapabilities =
  `com.joymusic.music.listentogether.proto`.ServerCapabilitiesKt.Dsl._create(this.toBuilder()).apply { block() }._build()

