// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializesuggestionApprovedPayload")
public inline fun suggestionApprovedPayload(block: com.joymusic.music.listentogether.proto.SuggestionApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload =
  com.joymusic.music.listentogether.proto.SuggestionApprovedPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.SuggestionApprovedPayload`
 */
public object SuggestionApprovedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload = _builder.build()

    /**
     * `string suggestionId = 1;`
     */
    public var suggestionId: kotlin.String
      @kotlin.jvm.JvmName("getSuggestionId")
        get() = _builder.suggestionId
      @kotlin.jvm.JvmName("setSuggestionId")
        set(value) {
        _builder.suggestionId = value
      }
    /**
     * `string suggestionId = 1;`
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * `.listentogether.TrackInfo trackInfo = 2;`
     */
    public var trackInfo: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo
      @kotlin.jvm.JvmName("getTrackInfo")
        get() = _builder.trackInfo
      @kotlin.jvm.JvmName("setTrackInfo")
        set(value) {
        _builder.trackInfo = value
      }
    /**
     * `.listentogether.TrackInfo trackInfo = 2;`
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * `.listentogether.TrackInfo trackInfo = 2;`
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }

    public val SuggestionApprovedPayloadKt.Dsl.trackInfoOrNull: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo?
      get() = _builder.trackInfoOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload.copy(block: `com.joymusic.music.listentogether.proto`.SuggestionApprovedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayload =
  `com.joymusic.music.listentogether.proto`.SuggestionApprovedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.joymusic.music.listentogether.proto.Listentogether.SuggestionApprovedPayloadOrBuilder.trackInfoOrNull: com.joymusic.music.listentogether.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

