// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeuserJoinedPayload")
public inline fun userJoinedPayload(block: com.joymusic.music.listentogether.proto.UserJoinedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload =
  com.joymusic.music.listentogether.proto.UserJoinedPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.UserJoinedPayload`
 */
public object UserJoinedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload = _builder.build()

    /**
     * `string userId = 1;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string username = 2;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 2;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `.listentogether.UserInfo user = 3;`
     */
    public var user: com.joymusic.music.listentogether.proto.Listentogether.UserInfo
      @kotlin.jvm.JvmName("getUser")
        get() = _builder.user
      @kotlin.jvm.JvmName("setUser")
        set(value) {
        _builder.user = value
      }
    /**
     * `.listentogether.UserInfo user = 3;`
     */
    public fun clearUser() {
      _builder.clearUser()
    }
    /**
     * `.listentogether.UserInfo user = 3;`
     * @return Whether the user field is set.
     */
    public fun hasUser(): kotlin.Boolean {
      return _builder.hasUser()
    }

    public val UserJoinedPayloadKt.Dsl.userOrNull: com.joymusic.music.listentogether.proto.Listentogether.UserInfo?
      get() = _builder.userOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload.copy(block: `com.joymusic.music.listentogether.proto`.UserJoinedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayload =
  `com.joymusic.music.listentogether.proto`.UserJoinedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.joymusic.music.listentogether.proto.Listentogether.UserJoinedPayloadOrBuilder.userOrNull: com.joymusic.music.listentogether.proto.Listentogether.UserInfo?
  get() = if (hasUser()) getUser() else null

