// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeuserKickedPayload")
public inline fun userKickedPayload(block: com.joymusic.music.listentogether.proto.UserKickedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload =
  com.joymusic.music.listentogether.proto.UserKickedPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.UserKickedPayload`
 */
public object UserKickedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload = _builder.build()

    /**
     * `string userId = 1;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string reason = 2;`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 2;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload.copy(block: `com.joymusic.music.listentogether.proto`.UserKickedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.UserKickedPayload =
  `com.joymusic.music.listentogether.proto`.UserKickedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

