// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.joymusic.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeuserDisconnectedPayload")
public inline fun userDisconnectedPayload(block: com.joymusic.music.listentogether.proto.UserDisconnectedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload =
  com.joymusic.music.listentogether.proto.UserDisconnectedPayloadKt.Dsl._create(com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `listentogether.UserDisconnectedPayload`
 */
public object UserDisconnectedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload = _builder.build()

    /**
     * `string userId = 1;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string username = 2;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 2;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload.copy(block: `com.joymusic.music.listentogether.proto`.UserDisconnectedPayloadKt.Dsl.() -> kotlin.Unit): com.joymusic.music.listentogether.proto.Listentogether.UserDisconnectedPayload =
  `com.joymusic.music.listentogether.proto`.UserDisconnectedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

